### ISSUE TITLE
What exactly does cfg.TASK mean？

### ISSUE THREAD

**Issue by mudexuyan** [facebookresearch/TimeSformer#108]
When I run the SLOWFAST_8x8_R50.yaml, the following error occurs，I can't find useful information in config file.

Traceback (most recent call last):
  File "tools/run_net.py", line 50, in <module>
    main()
  File "tools/run_net.py", line 32, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/home/wy/TimeSformer-main/timesformer/utils/misc.py", line 300, in launch_job
    func(cfg=cfg)
  File "/home/wy/TimeSformer-main/tools/train_net.py", line 410, in train
    model = build_model(cfg)
  File "/home/wy/TimeSformer-main/timesformer/models/build.py", line 36, in build_model
    model = MODEL_REGISTRY.get(name)(cfg)
  File "/home/wy/TimeSformer-main/timesformer/models/video_model_builder.py", line 175, in __init__
    self._construct_network(cfg)
  File "/home/wy/TimeSformer-main/timesformer/models/video_model_builder.py", line 398, in _construct_network
    self.head_name = "head{}".format(cfg.TASK)
  File "/home/anaconda3/envs/timesformer/lib/python3.7/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: TASK

**Comment by Eurekaer** [comment]
Hello, I have the same problem as you, have you found a good solution? If you find a good way, I hope you can share it, thank you very much

**Comment by pucha48** [comment]
I got the same issue did somebody find the solution ?
