### ISSUE TITLE
Error When Training the Default TimeSformer

### ISSUE THREAD

**Issue by shahd-seddik** [facebookresearch/TimeSformer#35]
I get this error when I run the provided training command on Google Colab.

The command I am referencing is:
`!python tools/run_net.py \
  --cfg configs/Kinetics/TimeSformer_divST_8x32_224.yaml \
  DATA.PATH_TO_DATA_DIR path_to_your_dataset \
  NUM_GPUS 1 \
  TRAIN.BATCH_SIZE 8 \
`

The error I get:

-- Process 6 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/content/TimeSformer/timesformer/utils/multiprocessing.py", line 58, in run
    torch.cuda.set_device(local_rank)
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 261, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal

Please advise. Thank you in advance.

**Comment by gberta** [comment]
I imagine that this has to do with GPU 0 not being available on the machine that you are trying to use. However, I'm not 100% sure. Please let me know if you figure this out.

**Comment by wolfworld6** [comment]
> I get this error when I run the provided training command on Google Colab.
> 
> The command I am referencing is: `!python tools/run_net.py \ --cfg configs/Kinetics/TimeSformer_divST_8x32_224.yaml \ DATA.PATH_TO_DATA_DIR path_to_your_dataset \ NUM_GPUS 1 \ TRAIN.BATCH_SIZE 8 \ `
> 
> The error I get:
> 
> -- Process 6 terminated with the following error: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap fn(i, *args) File "/content/TimeSformer/timesformer/utils/multiprocessing.py", line 58, in run torch.cuda.set_device(local_rank) File "/usr/local/lib/python3.7/site-packages/torch/cuda/**init**.py", line 261, in set_device torch._C._cuda_setDevice(device) RuntimeError: CUDA error: invalid device ordinal
> 
> Please advise. Thank you in advance.

have you solved it？
