### ISSUE TITLE
ImportError: cannot import name '_LinearWithBias' from 'torch.nn.modules.linear'

### ISSUE THREAD

**Issue by weiwenying** [facebookresearch/TimeSformer#63]
When I run inference:
```bash
python tools/run_net.py \
  --cfg configs/Kinetics/TimeSformer_divST_8x32_224_TEST.yaml \
  DATA.PATH_TO_DATA_DIR path_to_your_dataset \
  TEST.CHECKPOINT_FILE_PATH path_to_your_checkpoint \
  TRAIN.ENABLE False \
```

raise error:

```bash
Traceback (most recent call last):
  File "tools/run_net.py", line 6, in <module>
    from timesformer.utils.misc import launch_job
  File "/home/weiwenying/projects/video/TimeSformer/timesformer/utils/misc.py", line 20, in <module>
    from timesformer.models.batchnorm_helper import SubBatchNorm3d
  File "/home/weiwenying/projects/video/TimeSformer/timesformer/models/__init__.py", line 5, in <module>
    from .video_model_builder import ResNet, SlowFast # noqa
  File "/home/weiwenying/projects/video/TimeSformer/timesformer/models/video_model_builder.py", line 12, in <module>
    from . import head_helper, resnet_helper, stem_helper
  File "/home/weiwenying/projects/video/TimeSformer/timesformer/models/resnet_helper.py", line 15, in <module>
    from torch.nn.modules.linear import _LinearWithBias
ImportError: cannot import name '_LinearWithBias' from 'torch.nn.modules.linear'
```

what happen?

**Comment by weiwenying** [comment]
When I use old version of pytorch, it's problem solved:

```bash
# my cuda version 10.2
conda install pytorch=1.8.1 torchvision cudatoolkit=10.2 -c pytorch
```

**Comment by sthoduka** [comment]
for pytorch-1.9, you can rename `_LinearWithBias` to `NonDynamicallyQuantizableLinear`. The change was introduced here: https://github.com/pytorch/pytorch/commit/0896c6b1f091e696f40742d3529a4c05f81718f4

**Comment by parthplc** [comment]
In "/home/weiwenying/projects/video/TimeSformer/timesformer/models/resnet_helper.py" file comment the line with _LinearWithBias import

**Comment by happyBroJk** [comment]
good answer

**Comment by happyBroJk** [comment]
> When I use old version of pytorch, it's problem solved:
> 
> ```shell
> # my cuda version 10.2
> conda install pytorch=1.8.1 torchvision cudatoolkit=10.2 -c pytorch
> ```

when i  do like you say,I have got the problem of this : ' ModuleNotFoundError: No module named 'torchvision.io'
I wonder that it is because the torchvision is not approirate or not match the pytorch=1.8.1 ?

**Comment by feib33** [comment]
> > When I use old version of pytorch, it's problem solved:
> > ```shell
> > # my cuda version 10.2
> > conda install pytorch=1.8.1 torchvision cudatoolkit=10.2 -c pytorch
> > ```
> 
> when i do like you say,I have got the problem of this : ' ModuleNotFoundError: No module named 'torchvision.io' I wonder that it is because the torchvision is not approirate or not match the pytorch=1.8.1 ?

I got same error after downgraded torch to 1.8.1 and I think that your guess is correct. The torchvision's version is not compatible with pytorch=1.8.1. The approriate one is 0.9.1

**Comment by XinyueZ** [comment]
Try the fork by this guy
https://github.com/wanchichen/TimeSformer
