### ISSUE TITLE
Training on custom dataset in Something-Something V2 format

### ISSUE THREAD

**Issue by parthplc** [facebookresearch/TimeSformer#80]
I followed all the instructions in the DATASET.md file creating two folders one 

"/home/ubuntu/framelist" containing
```
train.csv
val.csv
```

and another folder
"/home/ubuntu/allframes" containing
```
29389283/1.jpg
29389283/2.jpg
29389283/3.jpg
29389283/4.jpg

81379398/1.jpg
81379398/2.jpg
81379398/3.jpg
81379398/4.jpg

...
```
But when running the command

python tools/run_net.py   --cfg configs/Kinetics/TimeSformer_divST_8x32_224.yaml   DATA.PATH_TO_DATA_DIR /home/ubuntu/framelist  DATA.PATH_PREFIX /home/ubuntu/allframes  NUM_GPUS 1   TRAIN.BATCH_SIZE 2

it throws the error

```
[10/03 13:55:10][INFO] kinetics.py:  71: Constructing Kinetics train...
Traceback (most recent call last):
  File "tools/run_net.py", line 44, in <module>
    main()
  File "tools/run_net.py", line 29, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/home/ubuntu/TimeSformer/timesformer/utils/misc.py", line 300, in launch_job
    func(cfg=cfg)
  File "/home/ubuntu/TimeSformer/tools/train_net.py", line 425, in train
    train_loader = loader.construct_loader(cfg, "train")
  File "/home/ubuntu/TimeSformer/timesformer/datasets/loader.py", line 82, in construct_loader
    dataset = build_dataset(dataset_name, cfg, split)
  File "/home/ubuntu/TimeSformer/timesformer/datasets/build.py", line 30, in build_dataset
    return DATASET_REGISTRY.get(name)(cfg, split)
  File "/home/ubuntu/TimeSformer/timesformer/datasets/kinetics.py", line 72, in __init__
    self._construct_loader()
  File "/home/ubuntu/TimeSformer/timesformer/datasets/kinetics.py", line 92, in _construct_loader
    == 2
AssertionError
```
@gberta can you please help me figure what is going wrong here and how can rectify it?

**Comment by gberta** [comment]
You need to change the dataset related entries in your configuration file. You are using Kinetics configurations now, which have a different data loader structure.

**Comment by parthplc** [comment]
Hey @gberta, thanks for the reply. Can you give some examples of which file to change and how if possible in Something-Something V2 format?

**Comment by gberta** [comment]
There are specific configurations for Something-Something-V2 in configs/SSv2. Please check those out.
