### ISSUE TITLE
Question about run_net.py

### ISSUE THREAD

**Issue by wssxjtu** [facebookresearch/TimeSformer#83]
hello！I need your help as a beginner！
I encountered a problem: When I run the following code, the command window prompts AssertionError
`TimeSformer-main$ python tools/run_net.py  \
> --cfg configs/Kinetics/TimeSformer_divST_8x32_224.yaml \
>   DATA.PATH_TO_DATA_DIR /data0/user/Kinetics-400/kinetics400 \
> NUM_GPUS 1 \
> TRAIN.BATCH_SIZE 8
`
Command window feedback
`[10/25 21:36:54][INFO] kinetics.py:  71: Constructing Kinetics train...
Traceback (most recent call last):
  File "tools/run_net.py", line 44, in <module>
    main()
  File "tools/run_net.py", line 29, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/home/user/TimeSformer-main/timesformer/utils/misc.py", line 300, in launch_job
    func(cfg=cfg)
  File "/home/user/TimeSformer-main/tools/train_net.py", line 425, in train
    train_loader = loader.construct_loader(cfg, "train")
  File "/home/user/TimeSformer-main/timesformer/datasets/loader.py", line 82, in construct_loader
    dataset = build_dataset(dataset_name, cfg, split)
  File "/home/user/TimeSformer-main/timesformer/datasets/build.py", line 30, in build_dataset
    return DATASET_REGISTRY.get(name)(cfg, split)
  File "/home/user/TimeSformer-main/timesformer/datasets/kinetics.py", line 72, in __init__
    self._construct_loader()
  File "/home/user/TimeSformer-main/timesformer/datasets/kinetics.py", line 92, in _construct_loader
    == 2
AssertionError
`

**Comment by gberta** [comment]
It seems that your .csv  dataset files are formatted incorrectly. Each of them should contain two columns: (1) path to the video, (2) label id.

**Comment by wssxjtu** [comment]
> It seems that your .csv dataset files are formatted incorrectly. Each of them should contain two columns: (1) path to the video, (2) label id.

I have solved my problem, thank you for your answer！

**Comment by serafinaLi** [comment]
hello,I have the same problem,but my .csv dataset files contain two columns.So I want to know how to solved this problem,thank you very much!
